# Generated by Django 2.2.3 on 2020-04-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0012_set_dj_partial_indexes'),
        ('base', '0003_auto_20200330_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misago_threads.Thread'),
        ),
    ]
