# Generated by Django 2.2.3 on 2020-04-05 15:03

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_article_related_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
    ]
