# Generated by Django 2.2.3 on 2020-04-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='related_discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misago_threads.Thread'),
        ),
    ]
