dist: trusty
services:
  - docker
addons:
  ssh_known_hosts: 'hts.radikal.jetzt'

script:
  - docker build .

before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in .maintain/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
# - provider: script
#   script: ssh root@hts.radikal.jetzt "cd /root/unterbau/radikal.jetzt/hts-staging && git fetch && git checkout $TRAVIS_BRANCH && git pull && bash scripts/deploy.sh"
#   on:
#     branch: develop
#     condition: "$TRAVIS_PULL_REQUEST = false"
- provider: script
  script: ssh root@hts.radikal.jetzt "cd /root/unterbau/radikal.jetzt/hts && git fetch && git checkout $TRAVIS_BRANCH && git pull && bash .maintain/deploy.sh"
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"