version: '2'

services:
  hts-db:
    environment:
      POSTGRES_DB: hts_db
      POSTGRES_USER: hts_user
      POSTGRES_PASSWORD: changeme
    restart: unless-stopped
    image: postgres:12
    volumes:
      - ./data/db:/var/lib/postgresql/data:rw
    expose:
      - "5432"
  hts-redis:
    restart: unless-stopped
    image: redis:3.0
    expose:
      - "6379"
  hts-app:
    environment:
      DATABASE_URL: postgres://hts_user:changeme@hts-db/hts_db
      CACHE_URL: redis://redis
    build:
      context: .
      dockerfile: ./.maintain/Dockerfile
    volumes:
      - ./data/media:/code/media
      - ./data/static:/code/static
    links:
      - hts-db:hts-db
      - hts-redis:hts-redis
    expose:
      - "8000"
