"""
Django settings for hts project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from misago import load_plugin_list_if_exists


PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/


# Application definition


AUTHENTICATION_BACKENDS = ["misago.users.authbackends.MisagoBackend"]

CSRF_FAILURE_VIEW = "misago.core.errorpages.csrf_failure"

PLUGINS_LIST_PATH = os.path.join(os.path.dirname(BASE_DIR), "plugins.txt")

INSTALLED_PLUGINS = load_plugin_list_if_exists(PLUGINS_LIST_PATH) or []

INSTALLED_APPS = INSTALLED_PLUGINS + [

    # Misago overrides for Django core feature
    "misago",
    "misago.users",

    # our pages
    'hts.base',
    'hts.search',

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.contrib.modeladmin',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',

    'modelcluster',
    'taggit',
    'django_extensions',
    'bootstrap4',
    'instance_selector',
    'fontawesome',
    'wagtailmetadata',

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.postgres",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # 3rd party apps used by Misago
    "ariadne.contrib.django",
    "celery",
    "debug_toolbar",
    "mptt",
    "rest_framework",
    "social_django",
    # Misago apps
    "misago.admin",
    "misago.acl",
    "misago.analytics",
    "misago.cache",
    "misago.core",
    "misago.conf",
    "misago.icons",
    "misago.themes",
    "misago.markup",
    "misago.legal",
    "misago.categories",
    "misago.threads",
    "misago.readtracker",
    "misago.search",
    "misago.socialauth",
    "misago.graphql",
    "misago.faker",
    "misago.menus",
    "misago.sso",
    "misago.plugins",

    # Menus
    'wagtailmenus',

    # Design / CSS
    'sass_processor',
    'compressor',
]

AUTH_USER_MODEL = "misago_users.User"

LOGIN_REDIRECT_URL = "wagtailadmin_home"

LOGIN_URL = "misago:login"

LOGOUT_URL = "misago:logout"

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "misago.users.middleware.RealIPMiddleware",
    "misago.core.middleware.FrontendContextMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "misago.cache.middleware.cache_versions_middleware",
    "misago.conf.middleware.dynamic_settings_middleware",
    "misago.socialauth.middleware.socialauth_providers_middleware",
    "misago.users.middleware.UserMiddleware",
    "misago.acl.middleware.user_acl_middleware",
    "misago.core.middleware.ExceptionHandlerMiddleware",
    "misago.users.middleware.OnlineTrackerMiddleware",
    "misago.admin.middleware.AdminAuthMiddleware",
    "misago.threads.middleware.UnreadThreadsCountMiddleware",
    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'hts.urls'

SOCIAL_AUTH_STRATEGY = "misago.socialauth.strategy.MisagoStrategy"

SOCIAL_AUTH_PIPELINE = (
    # Steps required by social pipeline to work - don't delete those!
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.social_user",
    # If enabled in admin panel, lets your users to associate their old forum account
    # with social one, if both have same e-mail address.
    "misago.socialauth.pipeline.associate_by_email",
    # Those steps make sure banned users may not join your site or use banned name or email.
    "misago.socialauth.pipeline.validate_ip_not_banned",
    "misago.socialauth.pipeline.validate_user_not_banned",
    # Reads user data received from social site and tries to create valid and available username
    # Required if you want automatic account creation to work. Otherwise optional.
    "misago.socialauth.pipeline.get_username",
    # Uncomment next line to enable automatic account creation if data from social site is valid
    # and get_username found valid name for new user account:
    # 'misago.socialauth.pipeline.create_user',
    # This step asks user to complete simple, pre filled registration form containing username,
    # email, legal note if you remove it without adding custom one, users will have no fallback
    # for joining your site using their social account.
    "misago.socialauth.pipeline.create_user_with_form",
    # Steps finalizing social authentication flow - don't delete those!
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "misago.socialauth.pipeline.require_activation",
)

SOCIAL_AUTH_POSTGRES_JSONFIELD = True


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.request",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'wagtail.contrib.settings.context_processors.settings',

                # menus
                'wagtailmenus.context_processors.wagtailmenus',

                "misago.acl.context_processors.user_acl",
                "misago.conf.context_processors.conf",
                "misago.conf.context_processors.og_image",
                "misago.core.context_processors.misago_version",
                "misago.core.context_processors.request_path",
                "misago.core.context_processors.momentjs_locale",
                "misago.icons.context_processors.icons",
                "misago.search.context_processors.search_providers",
                "misago.themes.context_processors.theme",
                "misago.legal.context_processors.legal_links",
                "misago.menus.context_processors.menus",
                "misago.users.context_processors.user_links",
                "misago.core.context_processors.hooks",
                # Data preloaders
                "misago.conf.context_processors.preload_settings_json",
                "misago.core.context_processors.current_link",
                "misago.markup.context_processors.preload_api_url",
                "misago.threads.context_processors.preload_threads_urls",
                "misago.users.context_processors.preload_user_json",
                "misago.socialauth.context_processors.preload_socialauth_json",
                # Note: keep frontend_context processor last for previous processors
                # to be able to expose data UI app via request.frontend_context
                "misago.core.context_processors.frontend_context",
            ]
        },
    }
]

WSGI_APPLICATION = 'hts.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "hts_dev",
        "HOST": "localhost",
        "PORT": 5432
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Django Rest Framework
# http://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "misago.core.rest_permissions.IsAuthenticatedOrReadOnly"
    ],
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "EXCEPTION_HANDLER": "misago.core.exceptionhandler.handle_api_exception",
    "UNAUTHENTICATED_USER": "misago.users.models.AnonymousUser",
    "URL_FORMAT_OVERRIDE": None,
}


# Celery - Distributed Task Queue
# http://docs.celeryproject.org/en/latest/userguide/configuration.html

# Configure Celery to use Redis as message broker.

CELERY_BROKER_URL = "redis://redis:6379/0"

# Celery workers may leak the memory, eventually depriving the instance of resources.
# This setting forces celery to stop worker, clean after it and create new one
# after worker has processed 10 tasks.

CELERY_WORKER_MAX_TASKS_PER_CHILD = 10

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# INTERNAL_IPS = [
#     '127.0.0.1',
# ]

# Caching
# https://docs.djangoproject.com/en/1.11/topics/cache/#setting-up-the-cache
MISAGO_SEARCH_CONFIG = "german"
CACHES = {
    "default": {
        # Misago doesn't run well with LocMemCache in production environments
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache"
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)


STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
]

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# Javascript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/3.0/ref/contrib/staticfiles/#manifeststaticfilesstorage
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Wagtail settings

WAGTAIL_SITE_NAME = "hts"

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_URL = 'http://example.com'

# CUSTOMISATIONS

BUBBLES = [
    "M153.5,-174.6C199.5,-144.4,237.6,-96.5,235.5,-50.1C233.5,-3.7,191.2,41.1,154.9,75.7C118.6,110.3,88.2,134.5,47.6,163.4C7.1,192.3,-43.7,225.8,-90.5,220.9C-137.4,215.9,-180.4,172.5,-212.5,120.8C-244.5,69.2,-265.5,9.3,-257.4,-46.9C-249.3,-103.1,-212.1,-155.8,-164.3,-185.7C-116.6,-215.6,-58.3,-222.8,-2.2,-220.1C53.8,-217.4,107.6,-204.9,153.5,-174.6Z",
    "M150.5,-181.7C197.3,-140.1,239,-94.8,234.7,-51.4C230.4,-8,180.2,33.5,150.2,88C120.2,142.4,110.6,209.8,73.1,240.8C35.6,271.9,-29.8,266.6,-86,243.1C-142.2,219.7,-189.3,178.1,-215.6,127.1C-242,76.1,-247.5,15.7,-238.9,-43.6C-230.2,-103,-207.4,-161.4,-165.2,-203.8C-123,-246.2,-61.5,-272.6,-4.8,-266.9C51.9,-261.1,103.7,-223.3,150.5,-181.7Z",
    "M153.5,-174.6C199.5,-144.4,237.6,-96.5,235.5,-50.1C233.5,-3.7,191.2,41.1,154.9,75.7C118.6,110.3,88.2,134.5,47.6,163.4C7.1,192.3,-43.7,225.8,-90.5,220.9C-137.4,215.9,-180.4,172.5,-212.5,120.8C-244.5,69.2,-265.5,9.3,-257.4,-46.9C-249.3,-103.1,-212.1,-155.8,-164.3,-185.7C-116.6,-215.6,-58.3,-222.8,-2.2,-220.1C53.8,-217.4,107.6,-204.9,153.5,-174.6Z",
    "M121.9,-128.6C168.9,-105.9,225.3,-77.8,229.3,-42.3C233.4,-6.8,185.1,36.1,154,87.8C122.8,139.4,108.8,199.9,71.3,227.1C33.7,254.3,-27.2,248.4,-85.3,229.4C-143.4,210.5,-198.6,178.5,-229.5,130C-260.4,81.6,-267.1,16.7,-252.3,-40.6C-237.6,-97.8,-201.4,-147.3,-155.8,-170.3C-110.1,-193.2,-55.1,-189.6,-8.8,-179.2C37.5,-168.7,75,-151.4,121.9,-128.6Z",
    "M156.5,-197.8C185.7,-162,180.5,-96.4,181.9,-39.4C183.3,17.7,191.2,66.4,178.4,116.5C165.5,166.6,131.8,218.1,81.6,245.8C31.4,273.5,-35.5,277.2,-79.1,248C-122.7,218.8,-143.2,156.7,-164.9,103C-186.6,49.3,-209.5,4.2,-205.5,-39.3C-201.4,-82.7,-170.5,-124.5,-131.7,-158.7C-93,-192.8,-46.5,-219.4,8.6,-229.6C63.6,-239.8,127.3,-233.7,156.5,-197.8Z",
    "M123.3,-144.3C163.6,-113.3,202.4,-77.9,209.9,-36.8C217.4,4.300000000000001,193.6,51.2,167.8,97.9C142,144.6,114.3,191.2,75.3,204.3C36.3,217.4,-14,197,-58.8,174.9C-103.5,152.8,-142.7,128.9,-176.8,91.5C-210.9,54.2,-239.9,3.4,-238.4,-48.4C-236.9,-100.3,-204.9,-153.2,-160.1,-183.4C-115.3,-213.7,-57.6,-221.4,-8,-211.8C41.6,-202.2,83.1,-175.4,123.3,-144.3Z",
    "M119.6,-139.9C153.1,-114.5,177,-74.9,178.7,-35.9C180.4,3.2,159.9,41.9,136.6,75.8C113.4,109.7,87.3,139,53.5,154.7C19.6,170.4,-22,172.6,-69.3,166C-116.6,159.4,-169.6,143.9,-194.8,108.5C-219.9,73,-217.3,17.6,-207.6,-36.5C-198,-90.6,-181.3,-143.4,-145.5,-168.4C-109.7,-193.4,-54.9,-190.7,-5.9,-183.7C43.1,-176.7,86.1,-165.3,119.6,-139.9Z",
    "M129.3,-147C175.4,-115.3,226.1,-82.1,245.1,-34.3C264.2,13.5,251.6,75.7,219.7,123C187.9,170.3,136.7,202.6,83.8,215.5C30.9,228.3,-23.7,221.8,-77.7,205.5C-131.6,189.3,-184.9,163.4,-200.1,122.6C-215.2,81.7,-192.3,25.9,-169.9,-17.6C-147.4,-61,-125.5,-92.2,-97.2,-127C-69,-161.9,-34.5,-200.4,3.5,-204.7C41.6,-208.9,83.1,-178.7,129.3,-147Z",
    "M117.4,-139.9C154.7,-108.6,189.1,-74,193.3,-36.2C197.5,1.6999999999999993,171.5,42.9,150.1,93C128.7,143.1,111.9,202.2,71.5,232.5C31.1,262.8,-32.8,264.4,-77.8,237.7C-122.8,211,-148.9,156,-178.4,103.6C-207.9,51.2,-240.8,1.5,-232,-39.6C-223.2,-80.7,-172.7,-113.1,-127,-142.9C-81.4,-172.7,-40.7,-199.8,-0.2999999999999998,-199.5C40.1,-199.1,80.1,-171.2,117.4,-139.9Z",
    "M171.1,-204C219.7,-163.2,255.6,-107.3,249.9,-56.4C244.3,-5.4,197,40.5,157.5,73.8C117.9,107.2,86,127.8,44,160.2C1.8999999999999986,192.6,-50.2,236.8,-98.9,235C-147.6,233.1,-192.9,185.3,-205.5,133.3C-218.2,81.2,-198.2,24.9,-185.2,-29.8C-172.2,-84.5,-166.1,-137.6,-136.4,-181.7C-106.7,-225.8,-53.4,-260.9,4,-265.6C61.3,-270.4,122.6,-244.7,171.1,-204Z",
    "M144.7,-163.7C185.2,-138.4,214.2,-90.6,217.5,-42.7C220.8,5.200000000000001,198.3,53.4,166.6,84.8C134.9,116.2,93.9,130.9,48.6,158C3.3000000000000007,185.1,-46.4,224.6,-78.9,214C-111.4,203.4,-126.7,142.7,-156.7,90.6C-186.6,38.5,-231.2,-5.100000000000001,-225.2,-39.8C-219.2,-74.5,-162.6,-100.5,-116.7,-124.9C-70.7,-149.3,-35.4,-172.1,8.399999999999999,-182.1C52.1,-192,104.1,-189.1,144.7,-163.7Z",
    "M117.8,-141.1C155.1,-109.2,189.3,-74.3,209.2,-27.2C229,19.9,234.4,79.2,213,129.1C191.5,179.1,143.1,219.7,87.9,238.6C32.6,257.5,-29.5,254.7,-67.8,224.3C-106.1,193.9,-120.6,135.9,-144.4,87.1C-168.2,38.2,-201.3,-1.6,-202,-42.3C-202.8,-83,-171.1,-124.6,-132.1,-156.2C-93,-187.8,-46.5,-209.4,-3.0999999999999996,-205.7C40.3,-202,80.6,-173,117.8,-141.1Z",
    "M136.6,-173.9C172,-133,192.4,-85.3,208.1,-31.5C223.8,22.3,234.9,82.2,216.2,134.5C197.5,186.8,149,231.5,93.3,248.3C37.6,265,-25.3,253.7,-80.5,229.8C-135.6,206,-183,169.5,-212.9,121.2C-242.9,72.9,-255.4,12.8,-238.1,-34.5C-220.8,-81.8,-173.7,-116.4,-129.1,-155.6C-84.4,-194.9,-42.2,-239,4.2,-243.9C50.6,-248.9,101.1,-214.9,136.6,-173.9Z"
]